
// Objective-C API for talking to the following Go packages
//
//	github.com/xtls/libxray
//
// File is generated by gomobile bind. Do not edit.
#ifndef __LibXray_FRAMEWORK_H__
#define __LibXray_FRAMEWORK_H__

#include "LibXray.objc.h"
#include "Universe.objc.h"

#endif
