name: AntiDPIVPN
options:
  bundleIdPrefix: com.truvvor
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.4"

targets:
  AntiDPIVPN:
    type: application
    platform: iOS
    sources:
      - path: AntiDPIVPN
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.truvvor.secureconnect
        INFOPLIST_FILE: AntiDPIVPN/Info.plist
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        FRAMEWORK_SEARCH_PATHS: "$(PROJECT_DIR)"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WJWU38ALPB
        SWIFT_OBJC_BRIDGING_HEADER: "AntiDPIVPN/AntiDPIVPN-Bridging-Header.h"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"
        OTHER_LDFLAGS: ["-lresolv"]
        CODE_SIGN_ENTITLEMENTS: "AntiDPIVPN/AntiDPIVPN.entitlements"
    dependencies:
      - framework: LibXray.xcframework
        embed: true
      - target: PacketTunnelExtension

  PacketTunnelExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: PacketTunnelExtension
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.truvvor.secureconnect.tunnel
        INFOPLIST_FILE: PacketTunnelExtension/Info.plist
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        FRAMEWORK_SEARCH_PATHS: "$(PROJECT_DIR)"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WJWU38ALPB
        SWIFT_OBJC_BRIDGING_HEADER: "PacketTunnelExtension/PacketTunnelExtension-Bridging-Header.h"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks @executable_path/../../Frameworks"
        OTHER_LDFLAGS: ["-lresolv"]
        CODE_SIGN_ENTITLEMENTS: "PacketTunnelExtension/PacketTunnelExtension.entitlements"
    dependencies:
      - framework: LibXray.xcframework
        embed: false
      - framework: HevSocks5Tunnel.xcframework
        embed: false
