// Objective-C API for talking to github.com/xtls/libxray Go package.
//   gobind -lang=objc github.com/xtls/libxray
//
// File is generated by gobind. Do not edit.

#ifndef __LibXray_H__
#define __LibXray_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LibXrayCountGeoDataRequest;
@class LibXrayInitDnsRequest;
@class LibXrayRunXrayFromJSONRequest;
@class LibXrayRunXrayRequest;

@interface LibXrayCountGeoDataRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull datDir;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) NSString* _Nonnull geoType;
@end

@interface LibXrayInitDnsRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull dns;
@property (nonatomic) NSString* _Nonnull deviceName;
@end

@interface LibXrayRunXrayFromJSONRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull datDir;
@property (nonatomic) NSString* _Nonnull mphCachePath;
@property (nonatomic) NSString* _Nonnull configJSON;
@end

@interface LibXrayRunXrayRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull datDir;
@property (nonatomic) NSString* _Nonnull mphCachePath;
@property (nonatomic) NSString* _Nonnull configPath;
@end

/**
 * Build Mph Cache
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayBuildMphCache(NSString* _Nullable base64Text);

/**
 * Convert share text to XrayJson
support XrayJson, v2rayN plain text, v2rayN base64 text, Clash.Meta yaml
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayConvertShareLinksToXrayJson(NSString* _Nullable base64Text);

/**
 * Convert XrayJson to share links.
VMess will generate VMessAEAD link.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayConvertXrayJsonToShareLinks(NSString* _Nullable base64Text);

/**
 * Read geo data and write all codes to text file.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayCountGeoData(NSString* _Nullable base64Text);

/**
 * Wrapper of nodep.GetFreePorts
count means how many ports you need.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayGetFreePorts(long count);

/**
 * Get Xray State
 */
FOUNDATION_EXPORT BOOL LibXrayGetXrayState(void);

/**
 * Init Dns.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayInitDns(NSString* _Nullable base64Text);

/**
 * LibXrayFreeOSMemory forces the Go runtime to release unused memory
back to the OS. Called from iOS side on memory-pressure events.
 */
FOUNDATION_EXPORT void LibXrayLibXrayFreeOSMemory(void);

/**
 * Init Dns Request
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayNewInitDnsRequest(NSString* _Nullable dns, NSString* _Nullable deviceName, NSError* _Nullable* _Nullable error);

/**
 * Create Xray Run From JSON Request
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayNewXrayRunFromJSONRequest(NSString* _Nullable datDir, NSString* _Nullable mphCachePath, NSString* _Nullable configJSON, NSError* _Nullable* _Nullable error);

/**
 * Create Xray Run Request
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayNewXrayRunRequest(NSString* _Nullable datDir, NSString* _Nullable mphCachePath, NSString* _Nullable configPath, NSError* _Nullable* _Nullable error);

/**
 * Ping Xray config and get the delay of its outbound.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayPing(NSString* _Nullable base64Text);

/**
 * query inbound and outbound stats.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayQueryStats(NSString* _Nullable base64Text);

/**
 * thin geo data
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayReadGeoFiles(NSString* _Nullable base64Text);

FOUNDATION_EXPORT NSString* _Nonnull LibXrayResetDns(void);

/**
 * Run Xray instance.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayRunXray(NSString* _Nullable base64Text);

/**
 * Run Xray instance with JSON configuration.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayRunXrayFromJSON(NSString* _Nullable base64Text);

/**
 * SetTunFd sets the TUN file descriptor.
Call this BEFORE RunXray/RunXrayFromJSON.
 */
FOUNDATION_EXPORT void LibXraySetTunFd(int32_t fd);

/**
 * Stop Xray instance.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayStopXray(void);

/**
 * Test Xray Config.
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayTestXray(NSString* _Nullable base64Text);

/**
 * Xray's version
 */
FOUNDATION_EXPORT NSString* _Nonnull LibXrayXrayVersion(void);

#endif
